import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { CalendarClock, CalendarPlus, Clock3, Download, Flag, PlayCircle, X } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "../auth";
import { Empty, Metric, PageTitle, Panel, StatusBadge } from "../components";
import { useFeedback } from "../feedback";
import { api, downloadBlob, errorMessage, isCanceledRequest, socket } from "../lib";
import type { Mission } from "../types";

const localDateTime = (offsetMs = 0) => { const date = new Date(Date.now() + offsetMs); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 19); };
const countdown = (scheduledFor: string | undefined, now: number) => { if (!scheduledFor) return "No launch time"; const seconds = Math.ceil((new Date(scheduledFor).getTime() - now) / 1000); if (seconds <= 0) return "Waiting for scheduler"; if (seconds < 60) return `Launch in ${seconds}s`; const minutes = Math.ceil(seconds / 60); return minutes < 60 ? `Launch in ${minutes}m` : `Launch in ${Math.ceil(minutes / 60)}h`; };

export default function FlightSchedule() {
  const { user } = useAuth(); const { notify, confirm } = useFeedback();
  const [items, setItems] = useState<Mission[]>([]); const [ready, setReady] = useState<Mission[]>([]); const [status, setStatus] = useState("ALL"); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [meta, setMeta] = useState({ page: 1, pages: 0, total: 0, dueToday: 0, counts: {} as Record<string, number> }); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [actionBusy, setActionBusy] = useState<string>(); const [exporting, setExporting] = useState(false); const requestRef = useRef<AbortController | null>(null);
  const [form, setForm] = useState({ missionId: "", scheduledFor: localDateTime(60_000), priority: "NORMAL" });
  const [now, setNow] = useState(Date.now());
  const available = useMemo(() => ready.filter((mission) => !["SCHEDULED", "PROCESSING"].includes(mission.scheduleStatus ?? "NONE")), [ready]);
  const load = async () => { requestRef.current?.abort(); const controller = new AbortController(); requestRef.current = controller; setLoading(true); setError(""); try { const [queue, missions] = await Promise.all([api.get("/mission-schedule", { params: { scheduleStatus: status, dateFrom, dateTo, page, limit: 20, timezoneOffsetMinutes: new Date().getTimezoneOffset() }, signal: controller.signal }), api.get("/missions", { params: { status: "READY", limit: 100 }, signal: controller.signal })]); if (controller.signal.aborted) return; setItems(queue.data.data); setMeta(queue.data.meta); setReady(missions.data.data); } catch (reason: any) { if (!isCanceledRequest(reason)) setError(errorMessage(reason)); } finally { if (requestRef.current === controller) { requestRef.current = null; if (!controller.signal.aborted) setLoading(false); } } };
  const previousStatusRef = useRef(status);
  useEffect(() => {
    const statusChanged = previousStatusRef.current !== status;
    previousStatusRef.current = status;
    if (statusChanged && page !== 1) { setPage(1); return () => { requestRef.current?.abort(); }; }
    void load();
    return () => { requestRef.current?.abort(); };
  }, [status, dateFrom, dateTo, page]);
  useEffect(() => { const refresh = () => { void load(); }; socket.auth = { token: localStorage.getItem("drone-token") }; socket.on("mission:schedule", refresh); socket.on("mission:status", refresh); socket.on("connect", refresh); if (!socket.connected) socket.connect(); return () => { socket.off("mission:schedule", refresh); socket.off("mission:status", refresh); socket.off("connect", refresh); }; }, [status, dateFrom, dateTo, page]);
  useEffect(() => { if (!form.missionId && available[0]) setForm((current) => ({ ...current, missionId: available[0]._id })); }, [available]);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);

  const schedule = async (event: FormEvent) => { event.preventDefault(); if (actionBusy) return; setError(""); setActionBusy("schedule"); try { await api.post(`/missions/${form.missionId}/schedule`, { scheduledFor: new Date(form.scheduledFor).toISOString(), priority: form.priority }); setOpen(false); setForm({ missionId: "", scheduledFor: localDateTime(60_000), priority: "NORMAL" }); notify("Mission added to flight schedule", "success"); void load(); } catch (reason) { setError(errorMessage(reason)); } finally { setActionBusy(undefined); } };
  const cancel = async (mission: Mission) => { if (actionBusy) return; setActionBusy(mission._id); try { if (!await confirm({ title: "Cancel scheduled launch", message: `${mission.name} will remain available in the mission planner.`, confirmLabel: "Cancel schedule", danger: true })) return; await api.delete(`/missions/${mission._id}/schedule`); notify("Scheduled launch cancelled", "success"); void load(); } catch (reason) { notify(errorMessage(reason), "error"); } finally { setActionBusy(undefined); } };
  const exportSchedule = async () => { if (!meta.total || loading || actionBusy || exporting) return; setExporting(true); setError(""); try { const response = await api.get("/mission-schedule/export", { params: { scheduleStatus: status, dateFrom, dateTo, timezoneOffsetMinutes: new Date().getTimezoneOffset() }, responseType: "blob" }); downloadBlob(`mission-schedule-${new Date().toISOString().slice(0, 10)}.csv`, response.data); notify("All matching schedule records exported", "success"); } catch (reason) { setError(errorMessage(reason)); notify("Schedule export failed", "error"); } finally { setExporting(false); } };
  const dueToday = meta.dueToday ?? 0;

  return <>
    <PageTitle eyebrow="AUTOMATION" title="Flight schedule" text="Queue validated missions for automatic launch when their aircraft becomes available." action={<div className="action-row"><button className="secondary" onClick={() => void exportSchedule()} disabled={!meta.total || loading || !!actionBusy || exporting}><Download />{exporting ? "Exporting..." : "Export schedule CSV"}</button>{user?.role === "ADMIN" && <button className="primary" disabled={!available.length || !!actionBusy} onClick={() => setOpen(true)}><CalendarPlus />Schedule mission</button>}</div>} />
    {error && !open && <div className="form-error page-error">{error}</div>}
    <Panel className="schedule-filters"><div className="toolbar"><span className="history-label">Filter scheduled launch dates</span><label>FROM<input aria-label="Schedule date from" type="date" max={dateTo || undefined} value={dateFrom} onChange={(event) => { setDateFrom(event.target.value); setPage(1); }} disabled={!!actionBusy} /></label><label>TO<input aria-label="Schedule date to" type="date" min={dateFrom || undefined} value={dateTo} onChange={(event) => { setDateTo(event.target.value); setPage(1); }} disabled={!!actionBusy} /></label></div></Panel>
    <div className="metric-grid"><Metric label="QUEUED" value={meta.counts.SCHEDULED ?? 0} icon={<CalendarClock />} /><Metric label="DUE TODAY" value={dueToday} icon={<Clock3 />} /><Metric label="STARTED" value={meta.counts.STARTED ?? 0} icon={<PlayCircle />} /><Metric label="NEEDS ATTENTION" value={meta.counts.FAILED ?? 0} icon={<Flag />} /></div>
    <Panel><div className="toolbar"><span className="history-label"><CalendarClock />Automatic mission queue</span><span className="result-count">{meta.total} scheduled records</span><select value={status} onChange={(event) => setStatus(event.target.value)} disabled={!!actionBusy}><option>ALL</option><option>SCHEDULED</option><option>PROCESSING</option><option>STARTED</option><option>FAILED</option><option>CANCELLED</option></select></div><div className="schedule-list">{items.map((mission) => { const overdue = mission.scheduledFor && new Date(mission.scheduledFor).getTime() < now && mission.scheduleStatus === "SCHEDULED"; const rowBusy = actionBusy === mission._id; return <article key={mission._id} className={overdue ? "schedule-item overdue" : "schedule-item"}><time><b>{mission.scheduledFor ? new Date(mission.scheduledFor).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }) : "—"}</b><span>{mission.scheduledFor ? new Date(mission.scheduledFor).toLocaleDateString() : "Unscheduled"}</span></time><div><Link to={`/missions/${mission._id}`}>{mission.name}</Link><small>{typeof mission.droneId === "string" ? "Aircraft" : `${mission.droneId.droneCode} · ${mission.droneId.name}`}</small>{mission.scheduleStatus === "SCHEDULED" && <span className={overdue ? "schedule-countdown overdue" : "schedule-countdown"}>{countdown(mission.scheduledFor, now)}</span>}{mission.scheduleError && <em>{mission.scheduleError}</em>}</div><StatusBadge status={mission.priority ?? "NORMAL"} /><StatusBadge status={mission.scheduleStatus ?? "NONE"} />{user?.role === "ADMIN" && mission.scheduleStatus === "SCHEDULED" && <button className="secondary small" disabled={!!actionBusy} onClick={() => cancel(mission)}><X />{rowBusy ? "Cancelling..." : "Cancel"}</button>}</article>})}{!loading && !items.length && <Empty title="No scheduled missions" text="Choose a ready mission and assign an automatic launch time." />}{loading && <div className="loading">Loading flight schedule…</div>}</div><div className="pagination"><button className="secondary small" disabled={page <= 1 || loading || !!actionBusy} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Page {meta.page} of {Math.max(meta.pages, 1)}</span><button className="secondary small" disabled={page >= meta.pages || loading || !!actionBusy} onClick={() => setPage((value) => value + 1)}>Next</button></div></Panel>
    {open && <div className="modal-layer"><form className="modal" onSubmit={schedule}><header><div><p className="eyebrow">AUTOMATIC LAUNCH</p><h2>Schedule mission</h2></div><button type="button" className="icon-btn" disabled={!!actionBusy} onClick={() => { setOpen(false); setError(""); }}><X /></button></header>{error && <div className="form-error">{error}</div>}<div className="form-grid"><label>Mission<select value={form.missionId} onChange={(event) => setForm({ ...form, missionId: event.target.value })} disabled={!!actionBusy} required>{available.map((mission) => <option key={mission._id} value={mission._id}>{mission.name} · {typeof mission.droneId === "string" ? "Aircraft" : mission.droneId.droneCode}</option>)}</select></label><label>Priority<select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })} disabled={!!actionBusy}><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Launch time<input type="datetime-local" step="1" min={localDateTime()} value={form.scheduledFor} onChange={(event) => setForm({ ...form, scheduledFor: event.target.value })} disabled={!!actionBusy} required /></label><div className="schedule-presets"><span>Quick launch</span><button type="button" disabled={!!actionBusy} onClick={() => setForm({ ...form, scheduledFor: localDateTime(10_000) })}>10 seconds</button><button type="button" disabled={!!actionBusy} onClick={() => setForm({ ...form, scheduledFor: localDateTime(60_000) })}>1 minute</button><button type="button" disabled={!!actionBusy} onClick={() => setForm({ ...form, scheduledFor: localDateTime(300_000) })}>5 minutes</button></div></div><footer><button type="button" className="secondary" disabled={!!actionBusy} onClick={() => setOpen(false)}>Cancel</button><button className="primary" disabled={!!actionBusy}>{actionBusy === "schedule" ? "Scheduling..." : "Add to schedule"}</button></footer></form></div>}
  </>;
}
