import { useEffect, useRef, useState } from "react";
import { Activity, BellRing, CheckCircle2, Clock3, CloudSun, Download, Plane, Radio, RefreshCw, Route, TriangleAlert, Wifi } from "lucide-react";
import { Link } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertRow, Empty, Metric, PageTitle, Panel, StatusBadge } from "../components";
import { useFeedback } from "../feedback";
import {
  api,
  downloadBlob,
  errorMessage,
  formatDuration,
  missionProgress,
  missionProgressLabel,
  socket,
} from "../lib";
import { useConnectionStatus, useHealthDetails } from "../realtime";
import { routePatternLabel, type Alert, type Command, type Drone, type DroneReadiness, type EnvironmentSnapshot, type Flight, type Mission, type OperationalInsights, type Telemetry } from "../types";

type Summary = { totalDrones: number; online: number; activeFlights: number; activeAlerts: number; recentFlights: Flight[]; missionCounts: Record<string, number>; flightTotals: { distanceMeters: number; durationSeconds: number }; alertTypes: Array<{ type: string; count: number }>; topDrones: Array<{ droneCode: string; name: string; flights: number; distanceMeters: number }>; recentMissions: Mission[]; recentCommands: Command[] };
const empty: Summary = { totalDrones: 0, online: 0, activeFlights: 0, activeAlerts: 0, recentFlights: [], missionCounts: {}, flightTotals: { distanceMeters: 0, durationSeconds: 0 }, alertTypes: [], topDrones: [], recentMissions: [], recentCommands: [] };

export default function Overview() {
  const { notify } = useFeedback(); const { status: connection } = useConnectionStatus(); const { health, loading: healthLoading, error: healthError } = useHealthDetails(); const [summary, setSummary] = useState<Summary>(empty); const [drones, setDrones] = useState<Drone[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [runningMissions, setRunningMissions] = useState<Mission[]>([]); const [latestTelemetryByDrone, setLatestTelemetryByDrone] = useState<Record<string, Telemetry>>({}); const [insights, setInsights] = useState<OperationalInsights>(); const [environment, setEnvironment] = useState<EnvironmentSnapshot>(); const [readiness, setReadiness] = useState<{ items: DroneReadiness[]; summary: { total: number; ready: number; blocked: number; warnings: number } }>({ items: [], summary: { total: 0, ready: 0, blocked: 0, warnings: 0 } }); const [loading, setLoading] = useState(true); const [exportingInsights, setExportingInsights] = useState(false); const [error, setError] = useState(""); const requestRef = useRef<AbortController | null>(null); const insightsRequestRef = useRef<AbortController | null>(null); const refreshTimerRef = useRef<number | null>(null); const insightsTimerRef = useRef<number | null>(null); const environmentRequestRef = useRef<AbortController | null>(null);
  const load = (silent = false) => { requestRef.current?.abort(); const controller = new AbortController(); requestRef.current = controller; if (!silent) { setLoading(true); setError(""); } Promise.all([api.get("/dashboard/summary", { signal: controller.signal }), api.get("/drones", { signal: controller.signal }), api.get("/alerts", { params: { status: "ACTIVE", limit: 5 }, signal: controller.signal }), api.get("/drones/readiness", { signal: controller.signal }), api.get("/missions", { params: { status: "RUNNING", limit: 10 }, signal: controller.signal }), api.get("/flights/active/telemetry", { params: { limit: 1 }, signal: controller.signal }), api.get("/insights", { signal: controller.signal })]).then(([s, d, a, r, m, t, i]) => { if (controller.signal.aborted) return; setSummary({ ...empty, ...s.data.data }); setDrones(d.data.data); setAlerts(a.data.data); setRunningMissions(m.data.data as Mission[]); const latest = Object.fromEntries((t.data.data as Array<{ droneId?: string; telemetry: Telemetry[] }>).flatMap((item) => { const point = item.telemetry.at(-1); return item.droneId && point ? [[item.droneId, point] as const] : []; })); setLatestTelemetryByDrone(latest); setInsights(i.data.data as OperationalInsights); setReadiness(r.data.data); setError(""); }).catch((reason) => { if (reason?.code !== "ERR_CANCELED" && reason?.name !== "CanceledError") { setError(errorMessage(reason)); if (!silent) notify(errorMessage(reason), "error"); } }).finally(() => { if (requestRef.current === controller) { requestRef.current = null; if (!controller.signal.aborted) setLoading(false); } }); };
  const loadInsights = (silent = true) => { insightsRequestRef.current?.abort(); const controller = new AbortController(); insightsRequestRef.current = controller; api.get("/insights", { signal: controller.signal }).then((response) => { if (!controller.signal.aborted) setInsights(response.data.data as OperationalInsights); }).catch((reason) => { if (!silent && reason?.code !== "ERR_CANCELED" && reason?.name !== "CanceledError") { setError(errorMessage(reason)); notify(errorMessage(reason), "error"); } }).finally(() => { if (insightsRequestRef.current === controller) insightsRequestRef.current = null; }); };
  const loadEnvironment = (silent = true) => { environmentRequestRef.current?.abort(); const controller = new AbortController(); environmentRequestRef.current = controller; api.get("/environment", { signal: controller.signal }).then((response) => { if (!controller.signal.aborted) setEnvironment(response.data.data as EnvironmentSnapshot); }).catch((reason) => { if (!silent && reason?.code !== "ERR_CANCELED" && reason?.name !== "CanceledError") { setError(errorMessage(reason)); notify(errorMessage(reason), "error"); } }).finally(() => { if (environmentRequestRef.current === controller) environmentRequestRef.current = null; }); };
  const scheduleRefresh = () => { if (refreshTimerRef.current !== null) window.clearTimeout(refreshTimerRef.current); refreshTimerRef.current = window.setTimeout(() => { refreshTimerRef.current = null; load(true); }, 120); };
  const scheduleInsightsRefresh = () => { if (insightsTimerRef.current !== null) return; insightsTimerRef.current = window.setTimeout(() => { insightsTimerRef.current = null; loadInsights(); }, 3_000); };
  const exportInsights = async () => { if (!insights || exportingInsights) return; setExportingInsights(true); try { const response = await api.get("/insights/export", { responseType: "blob" }); downloadBlob(`operational-insights-${new Date().toISOString().slice(0, 10)}.csv`, response.data); notify("Operational insights snapshot exported", "success"); } catch (reason) { setError(errorMessage(reason)); notify("Insights export failed", "error"); } finally { setExportingInsights(false); } };
  useEffect(() => { load(); const timer = window.setInterval(scheduleRefresh, 30_000); const insightTimer = window.setInterval(() => loadInsights(), 10_000); socket.auth = { token: localStorage.getItem("drone-token") }; socket.on("alert:created", scheduleRefresh); socket.on("alert:updated", scheduleRefresh); socket.on("flight:status", scheduleRefresh); socket.on("mission:status", scheduleRefresh); socket.on("command:status", scheduleRefresh); socket.on("connect", scheduleRefresh); if (!socket.connected) socket.connect(); return () => { window.clearInterval(timer); window.clearInterval(insightTimer); if (refreshTimerRef.current !== null) { window.clearTimeout(refreshTimerRef.current); refreshTimerRef.current = null; } if (insightsTimerRef.current !== null) { window.clearTimeout(insightsTimerRef.current); insightsTimerRef.current = null; } socket.off("alert:created", scheduleRefresh); socket.off("alert:updated", scheduleRefresh); socket.off("flight:status", scheduleRefresh); socket.off("mission:status", scheduleRefresh); socket.off("command:status", scheduleRefresh); socket.off("connect", scheduleRefresh); requestRef.current?.abort(); insightsRequestRef.current?.abort(); }; }, []);
  useEffect(() => {
    loadEnvironment(false);
    const timer = window.setInterval(() => loadEnvironment(), 60_000);
    return () => { window.clearInterval(timer); environmentRequestRef.current?.abort(); };
  }, []);
  useEffect(() => {
    const refresh = scheduleRefresh;
    const events = ["drone:updated", "fleet:updated", "maintenance:updated", "geofence:updated", "mission:updated"];
    events.forEach((event) => socket.on(event, refresh));
    return () => events.forEach((event) => socket.off(event, refresh));
  }, []);
  useEffect(() => {
    const subscribe = () => socket.emit("subscribe:fleet");
    const telemetry = (payload: Telemetry) => {
      setLatestTelemetryByDrone((current) => {
        const previous = current[payload.droneId];
        if (previous && previous.flightId === payload.flightId && previous.sequence >= payload.sequence) return current;
        return { ...current, [payload.droneId]: payload };
      });
      scheduleInsightsRefresh();
    };
    socket.on("telemetry:update", telemetry);
    socket.on("connect", subscribe);
    if (socket.connected) subscribe();
    return () => { socket.off("telemetry:update", telemetry); socket.off("connect", subscribe); socket.emit("unsubscribe:fleet"); };
  }, []);
  if (loading) return <div className="dashboard-skeleton"><div /><div /><div /><div /><section /></div>;
  const droneById = new Map(drones.map((drone) => [drone._id, drone]));
  const blocked = readiness.items.filter((item) => !item.ready);
  const apiStatus = health ? health.status === "online" ? "ONLINE" : "DEGRADED" : healthLoading ? "CONNECTING" : "OFFLINE";
  const databaseStatus = health ? health.database === "connected" ? "ONLINE" : "OFFLINE" : healthLoading ? "CONNECTING" : "OFFLINE";
  return <><PageTitle eyebrow="COMMAND CENTER" title="Operational overview" text="Fleet readiness, mission outcomes and safety performance at a glance." action={<Link className="primary" to="/live"><Activity />Open live flight</Link>} />
    {error && <div className="form-error page-error" role="alert"><span>{error}</span><button className="secondary small" onClick={() => load()} disabled={loading}><RefreshCw />Retry</button></div>}
    <Panel className={`overview-readiness ${blocked.length ? "blocked" : "ready"}`} title="Launch readiness" action={<Link to="/live" className="text-link">Open preflight checks</Link>}><div className="overview-readiness-body"><strong>{readiness.summary.ready}<small> / {readiness.summary.total} READY</small></strong><div>{blocked.length ? blocked.slice(0, 4).map((item) => <span key={item.droneId}><TriangleAlert />{droneById.get(item.droneId)?.droneCode ?? "Aircraft"}: {item.blockers[0]}</span>) : readiness.summary.total ? <span className="all-ready"><CheckCircle2 />All aircraft passed preflight checks</span> : <span className="all-ready"><Plane />No aircraft registered yet · <Link to="/drones" className="text-link">Open fleet management</Link></span>}{blocked.length > 4 && <small>+{blocked.length - 4} more aircraft require attention</small>}</div></div></Panel>
    <Panel title="System health" action={<StatusBadge status={connection} />}><div className="system-health-grid"><HealthCell label="API" status={apiStatus} detail={health ? `Uptime ${formatUptime(health.uptimeSeconds)}` : healthError ? "Health endpoint unavailable" : "Checking endpoint"} /><HealthCell label="DATABASE" status={databaseStatus} detail={health?.databaseLatencyMs == null ? "No database ping" : `${health.databaseLatencyMs} ms ping`} /><HealthCell label="WEBSOCKET" status={connection} detail={connection === "ONLINE" ? "Realtime link active" : connection === "DEGRADED" ? "A core service needs attention" : "Waiting for reconnect"} /><HealthCell label="LAST CHECK" status={health ? "ONLINE" : "CONNECTING"} detail={health ? new Date(health.timestamp).toLocaleTimeString() : "Pending"} /></div></Panel>
    <div className="metric-grid"><Metric label="TOTAL DRONES" value={summary.totalDrones} icon={<Plane />} /><Metric label="CONNECTED" value={summary.online} icon={<Wifi />} /><Metric label="ACTIVE FLIGHTS" value={summary.activeFlights} icon={<Radio />} /><Metric label="ACTIVE ALERTS" value={summary.activeAlerts} icon={<BellRing />} /></div><EnvironmentQuick snapshot={environment} />
    <div className="metric-grid operations"><Metric label="MISSIONS COMPLETED" value={summary.missionCounts.COMPLETED ?? 0} icon={<CheckCircle2 />} /><Metric label="MISSIONS FAILED" value={summary.missionCounts.FAILED ?? 0} icon={<TriangleAlert />} /><Metric label="TOTAL DISTANCE" value={(summary.flightTotals.distanceMeters / 1000).toFixed(1)} unit="km" icon={<Route />} /><Metric label="TOTAL FLIGHT TIME" value={formatDuration(summary.flightTotals.durationSeconds)} icon={<Clock3 />} /></div>
    <Panel title="Operational insights" action={insights ? <span className="insights-action"><StatusBadge status={insights.risk.level} /><small>Updated {new Date(insights.generatedAt).toLocaleTimeString()}</small><button className="secondary small" onClick={() => void exportInsights()} disabled={exportingInsights}><Download />{exportingInsights ? "Exporting…" : "Export snapshot"}</button></span> : undefined}><div className={`insights-overview ${insights?.risk.level.toLowerCase() ?? ""}`}><div className="insights-risk"><span>FLIGHT RISK</span><strong>{insights?.risk.score ?? "—"}<small>/100</small></strong><b>{insights?.risk.level ?? "CHECKING"}</b></div><div className="insights-summary">{[ ["ACTIVE FLIGHTS", insights?.summary.activeFlights ?? "—"], ["ACTIVE ALERTS", insights?.summary.activeAlerts ?? "—"], ["STALE STREAMS", insights?.summary.staleTelemetry ?? "—"], ["OVERDUE SERVICE", insights?.summary.overdueMaintenance ?? "—"] ].map(([label, value]) => <span key={label}><b>{label}</b><strong>{value}</strong></span>)}</div><div className="insights-list">{(insights?.insights ?? []).slice(0, 4).map((insight) => <article className={`insight-item ${insight.severity.toLowerCase()}`} key={insight.key}><header><span>{insight.category}</span><StatusBadge status={insight.severity} /></header><b>{insight.title}</b><p>{insight.evidence}</p><small>{insight.confidence}% confidence · {insight.recommendation}</small>{insight.droneId ? <Link className="insight-link" to={`/drones/${insight.droneId}`}>Open {insight.droneCode ?? "aircraft"}</Link> : <Link className="insight-link" to="/alerts">Open alert center</Link>}</article>)}</div></div></Panel>
    <Panel title="Active mission progress" action={<Link to="/live" className="text-link">Open live control</Link>}><div className="mission-progress-list">{runningMissions.map((mission) => { const droneId = typeof mission.droneId === "string" ? mission.droneId : mission.droneId._id; const drone = typeof mission.droneId === "string" ? undefined : mission.droneId; const latest = latestTelemetryByDrone[droneId]; const progress = missionProgress(latest?.waypointIndex, latest?.waypointCount, latest?.flightPhase); return <Link to={`/missions/${mission._id}`} className="mission-progress-row" key={mission._id}><div className="mission-progress-summary"><span><b>{mission.name}</b><small>{drone?.droneCode ?? "Aircraft"} · {latest?.flightPhase?.replaceAll("_", " ") ?? "WAITING FOR TELEMETRY"}</small></span><strong>{progress ? `${progress.percent}%` : "—"}</strong></div><div className="mission-progress-meter" role="progressbar" aria-label={`${mission.name} progress`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress?.percent ?? 0}><i><em style={{ width: `${progress?.percent ?? 0}%` }} /></i></div><small className="mission-progress-detail">{progress ? `${progress.current}/${progress.total} waypoints · ${missionProgressLabel(latest?.waypointIndex, latest?.waypointCount, latest?.flightPhase)}` : "Awaiting the first telemetry packet"}</small></Link>})}{!runningMissions.length && <Empty title="No active missions" text="Mission progress appears here when a waypoint mission is running." />}</div></Panel>
    <div className="two-one-grid"><Panel title="Alert distribution"><div className="chart operations-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={summary.alertTypes}><CartesianGrid stroke="#202a36" vertical={false} /><XAxis dataKey="type" stroke="#64748b" tickLine={false} tickFormatter={(v) => v.replaceAll("_", " ")} fontSize={9} /><YAxis allowDecimals={false} stroke="#64748b" tickLine={false} /><Tooltip contentStyle={{ background: "#111822", border: "1px solid #273140", borderRadius: 8 }} /><Bar dataKey="count" fill="#3b82f6" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div>{!summary.alertTypes.length && <Empty title="No safety events" text="Alert analytics will appear after simulated anomalies." />}</Panel><Panel title="Most active aircraft"><div className="ranking-list">{summary.topDrones.map((drone, index) => <div key={drone.droneCode}><b>{index + 1}</b><span><strong>{drone.droneCode}</strong><small>{drone.flights} flights · {(drone.distanceMeters / 1000).toFixed(1)} km</small></span></div>)}{!summary.topDrones.length && <Empty title="No ranking yet" text="Complete flights to rank aircraft activity." />}</div></Panel></div>
    <div className="two-one-grid"><Panel title="Fleet status" action={<Link to="/drones" className="text-link">View fleet</Link>}><div className="fleet-list">{drones.slice(0, 5).map((drone) => <Link to={`/drones/${drone._id}`} key={drone._id} className="fleet-row"><span className="drone-icon"><Plane /></span><div><b>{drone.droneCode}</b><small>{drone.name} · {drone.model}</small></div><div className="battery-mini"><i style={{ width: `${drone.battery}%` }} /></div><span>{Math.round(drone.battery)}%</span><StatusBadge status={drone.status} /></Link>)}{!drones.length && <Empty title="No drones yet" text="Create your first drone to begin monitoring." />}</div></Panel><Panel title="Active alerts" action={<Link to="/alerts" className="text-link">Alert center</Link>}><div className="alerts-list">{alerts.map((alert) => <AlertRow key={alert._id} severity={alert.severity} message={alert.message} time={alert.occurredAt} />)}{!alerts.length && <Empty title="All clear" text="There are no active operational alerts." />}</div></Panel></div>
    <div className="two-one-grid"><Panel title="Recent missions" action={<Link to="/missions" className="text-link">Mission planner</Link>}><div className="table-wrap"><table><thead><tr><th>Mission</th><th>Drone</th><th>Waypoints</th><th>Status</th></tr></thead><tbody>{summary.recentMissions.map((mission) => <tr key={mission._id}><td><Link to={`/missions/${mission._id}`} className="row-link">{mission.name}</Link></td><td>{typeof mission.droneId === "string" ? "—" : mission.droneId.droneCode}</td><td>{mission.waypoints.length}</td><td><StatusBadge status={mission.status} /></td></tr>)}</tbody></table>{!summary.recentMissions.length && <Empty title="No missions" text="Create a waypoint mission to populate operational analytics." />}</div></Panel><Panel title="Recent commands" action={<Link to="/command-center" className="text-link">Command center</Link>}><div className="command-feed">{summary.recentCommands.map((command) => <div key={command._id}><span><b>{command.type.replace("_", " ")}</b><small>{typeof command.droneId === "string" ? "Aircraft" : command.droneId.droneCode} · {new Date(command.requestedAt).toLocaleTimeString()}</small></span><StatusBadge status={command.status} /></div>)}{!summary.recentCommands.length && <Empty title="No commands" text="Operator and system actions appear here." />}</div></Panel></div>
    <Panel title="Recent flight operations" action={<Link to="/history" className="text-link">Flight history</Link>}><div className="command-feed">{summary.recentFlights.map((flight) => <div key={flight._id}><span><b>{flight.flightCode}</b><small>{typeof flight.droneId === "string" ? "Aircraft" : flight.droneId.droneCode} · {routePatternLabel(flight.routePattern)} · {flight.flightPhase?.replaceAll("_", " ") ?? "MISSION"}</small></span><StatusBadge status={flight.status} /></div>)}{!summary.recentFlights.length && <Empty title="No flight operations" text="Start a simulation to populate the operational feed." />}</div></Panel></>;
}

function formatUptime(seconds: number) { const days = Math.floor(seconds / 86_400); const hours = Math.floor(seconds % 86_400 / 3_600); const minutes = Math.floor(seconds % 3_600 / 60); return days ? `${days}d ${hours}h` : hours ? `${hours}h ${minutes}m` : `${minutes}m`; }
function HealthCell({ label, status, detail }: { label: string; status: string; detail: string }) { return <div className="system-health-cell"><div><b>{label}</b><StatusBadge status={status} /></div><small>{detail}</small></div>; }
function EnvironmentQuick({ snapshot }: { snapshot?: EnvironmentSnapshot }) {
  if (!snapshot) return <Panel title="Environment snapshot"><div className="environment-quick-empty"><CloudSun /><span>Loading field conditions...</span></div></Panel>;
  const conditions = snapshot.conditions;
  return <Panel title="Environment snapshot" action={<Link to="/environment" className="text-link">Open environment</Link>}><div className={`environment-quick ${snapshot.flightRisk.level.toLowerCase()}`}><div className="environment-quick-risk"><CloudSun /><span><b>FLIGHT RISK</b><strong>{snapshot.flightRisk.score}<small>/100</small></strong></span><StatusBadge status={snapshot.flightRisk.level} /></div><div className="environment-quick-conditions"><span><b>TEMPERATURE</b><strong>{conditions.temperatureC.toFixed(1)}°C</strong></span><span><b>HUMIDITY</b><strong>{conditions.humidityPercent}%</strong></span><span><b>WIND</b><strong>{conditions.windSpeedMps.toFixed(1)} m/s {conditions.windDirection}</strong></span><span><b>VISIBILITY</b><strong>{conditions.visibilityKm.toFixed(1)} km</strong></span></div><small className="environment-quick-source">{snapshot.sourceLabel} · updated {new Date(snapshot.generatedAt).toLocaleTimeString()}</small></div></Panel>;
}
